### ISSUE TITLE
Cannot run usage example

### ISSUE THREAD

**Issue by pierredewilde** [davidpadbury/node-highcharts#3]
When I try to run usage example, I get:

```
buffer.js:156
        throw new Error('First argument needs to be a number, ' +
              ^
Error: First argument needs to be a number, array or string.
    at new Buffer (buffer.js:156:15)
    at fs.js:476:51
```

using `node-highcharts 0.0.2` with `node 0.4.12`.

**Comment by davidpadbury** [comment]
Yep - there's a bunch of problems due to changes in dependent libraries. Just having a quick bash at it now.

**Comment by nsilve** [comment]
I have also problems running the example with node-v0.6.10.

It returns:

<pre>
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: write EPIPE
    at errnoException (net.js:642:11)
    at Object.afterWrite [as oncomplete] (net.js:480:18)
</pre>

**Comment by bzarnett** [comment]
Any updates to resolving the issue indicated above:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: write EPIPE
    at errnoException (net.js:670:11)
    at Object.afterWrite [as oncomplete](net.js:503:19)

**Comment by davidpadbury** [comment]
I'm afraid I haven't had any time to look at this and no longer use node-highcharts actively.

**Comment by joaopedromatos** [comment]
Also getting the same error Error: write EPIPE
